name: goat-regtest

services:
  geth:
    image: ghcr.io/goatnetwork/goat-geth:testnet
    pull_policy: always
    stop_grace_period: 30s
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "geth attach --exec eth.blockNumber"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - --http
      - --http.api=eth,net,web3
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --syncmode=full
      - --bootnodes=enode://ffd38ce80d3e6b45f0ce5a78709a73d16a0d71eb331632d74be3b50c1521ee3802eb6fc7b1d65c68e281e97c8803503a753867cdafb353f28c022a0845266bd7@175.41.182.177:30303
    volumes:
      - /data/geth:/root/.ethereum
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

  goat:
    image: ghcr.io/goatnetwork/goat:testnet
    pull_policy: always
    stop_grace_period: 30s
    network_mode: host
    restart: unless-stopped
    command:
      - --home
      - /goat
      - --goat.geth
      - /geth/geth.ipc
      - --api.enable
      - --api.address=tcp://0.0.0.0:1317
      - --p2p.persistent_peers
      - 10732865500c75b9b51cd7ca6fb0155673e835a5@175.41.182.177:26656
    volumes:
      - /data/goat:/goat
      - /data/geth:/geth
    depends_on:
      geth:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
