name: goat-regtest

services:
  geth:
    image: anvztor/geth:latest
    container_name: goat-regtest-geth-1
    pull_policy: if_not_present
    stop_grace_period: 30s
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "geth attach --exec eth.blockNumber"]
      interval: 5s
      timeout: 5s
      retries: 5
    command:
      - --http
      - --http.api=eth,net,web3
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --syncmode=full
    ports:
      - 8545:8545
      - 8551:8551
      - 30303:30303
    volumes:
      - ./data/geth:/root/.ethereum

  goat:
    image: anvztor/goat:latest
    container_name: goat-regtest-goat-1
    pull_policy: if_not_present
    stop_grace_period: 30s
    restart: unless-stopped
    command:
      - --home
      - /goat
      - --goat.geth
      - /geth/geth.ipc
      - --api.enable
      - --api.address=tcp://0.0.0.0:1317
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --p2p.laddr=tcp://0.0.0.0:26656
    volumes:
      - ./data/goat:/goat
      - ./data/geth:/geth
    depends_on:
      geth:
        condition: service_healthy