name: goat-regtest

services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:${VERSION:-latest}
    container_name: bitcoin-regtest
    volumes:
      - ./data/bitcoin:/home/bitcoin/.bitcoin
    ports:
      - 18443:18443
      - 18444:18444
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        bitcoind -regtest -datadir=/home/bitcoin/.bitcoin -daemon -regtest=1 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -txindex=1 -reindex=1 -fallbackfee=0.01 -rpcuser=test -rpcpassword=test -discover=0 -server=1
        sleep 10

        # Load wallet
        bitcoin-wallet -regtest -wallet=demo create
        mkdir -p /home/bitcoin/.bitcoin/regtest/wallets/demo/
        cp /root/.bitcoin/regtest/wallets/demo/wallet.dat /home/bitcoin/.bitcoin/regtest/wallets/demo/wallet.dat
        cd /home/bitcoin/.bitcoin/regtest/wallets/
        chmod 777 -R demo/
        bitcoin-cli -regtest -rpcuser=test -rpcpassword=test loadwallet demo
        
        # Generate 199 blocks to get miner reward, execute only during initialization
        if [ $(bitcoin-cli -regtest -rpcuser=test -rpcpassword=test getblockcount) -le 199 ]; then
          bitcoin-cli -regtest -rpcuser=test -rpcpassword=test -generate 199
          bitcoin-cli -regtest -rpcuser=test -rpcpassword=test sendtoaddress bcrt1qksncyqxd4857fa8uadklcj56a5g45zmqvmzccq 100
          bitcoin-cli -regtest -rpcuser=test -rpcpassword=test -generate 1
        fi

        # Generate 1 block every 2 minutes by default, modify the interval as needed
        while true; do
          bitcoin-cli -regtest -rpcuser=test -rpcpassword=test -generate 1
          sleep 120
        done

        tail -f /dev/null
    networks:
      - goat_network

networks:
  goat_network:
    external: true
