name: goat-regtest-genesis

services:
  geth:
    image: anvztor/geth:latest
    pull_policy: always
    command:
      - init
      - --cache.preimages=true
      - /genesis/geth.json
    volumes:
      - /data/geth:/root/.ethereum
      - ./genesis:/genesis

  goat:
    image: anvztor/goat:latest
    pull_policy: always
    entrypoint: ["sh", "-c"]
    command:
      - "goatd init --home /goat devnet && cp /genesis/goat.json /goat/config/genesis.json"
    volumes:
      - /data/goat:/goat
      - ./genesis:/genesis
