name: goat-regtest-genesis

services:
  geth:
    image: ghcr.io/goatnetwork/goat-geth:testnet
    pull_policy: always
    command:
      - init
      - --cache.preimages=true
      - /genesis/geth.json
    volumes:
      - /data/geth:/root/.ethereum
      - ./genesis:/genesis

  goat:
    image: ghcr.io/goatnetwork/goat:testnet
    pull_policy: always
    entrypoint: ["sh", "-c"]
    command:
      - "goatd init --home /goat devnet && cp /genesis/goat.json /goat/config/genesis.json"
    volumes:
      - /data/goat:/goat
      - ./genesis:/genesis
